# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pdf"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Alexandrov"]
  s.date = "2012-03-09"
  s.description = "pdf uses the shell utility wkhtmltopdf to serve a PDF file to a user from HTML. In other words, rather than dealing with a PDF generation DSL of some sort, you simply write an HTML view as you would normally, and let pdf take care of the hard stuff."
  s.email = "igor.alexandrov@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "generators/pdf/pdf_generator.rb",
    "generators/pdf/templates/configure_pdf.rb",
    "lib/generators/pdf_generator.rb",
    "lib/pdf.rb",
    "lib/pdf/configuration.rb",
    "lib/pdf/errors.rb",
    "lib/pdf/helper.rb",
    "lib/pdf/rails.rb",
    "lib/pdf/rails/engine.rb",
    "lib/pdf/rails/legacy.rb",
    "lib/pdf/rails/railtie.rb",
    "lib/pdf/render.rb",
    "lib/pdf/tempfile.rb",
    "lib/pdf/writer.rb",
    "test/fixtures/wicked.css",
    "test/helper_test.rb",
    "test/test_helper.rb",
    "test/wicked_pdf_helper_test.rb",
    "test/writer_test.rb"
  ]
  s.homepage = "http://github.com/igor-alexandrov/pdf"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "PDF generator for Ruby on Rails"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

